### ISSUE TITLE
Selective Application Tunneling

### ISSUE THREAD

**Issue by jonpolak** [pirate/wireguard-docs#30]
Can you cover the usecase where wireguard is ran out of a separate network namespace wherein certain applications are launched -- and only the traffic of those launched from that network namespace is tunneled? I've been doing this on OpenVpn for a years but as Ubuntu's adoption of  `systemd-resolved ` I've had DNS leaks. 

Would love if there was a wireguard native way to tunnel certain applications rather than tunnel traffic based on range of destination IP addresses. 

Ps. thanks for the HN post.

**Comment by pirate** [comment]
By certain applications do you mean certain ports, or unix sockets, or something else?

I believe the wireguard userspace implementations let you do anyting you want with the wireguard connection, so you could conceivably bind an application to a wg connection with a small userspace program without needing to use a tun/tap interface + assign it a real port.  It could work something like a CloudFlare's Argo tunnels https://www.cloudflare.com/en-ca/products/argo-tunnel/

**Comment by jonpolak** [comment]
The use case would be - I have say firefox going through the tunnel while chrome is not tunneled. shell utilities like `ping` , `dig`  and  (very importantly)  `systemd-resolved`  need to point them either to the tunnel or to the untunneled interface.  This is poorly documented. For openvpn I've used [this script](https://github.com/crasm/vpnshift.sh/blob/master/vpnshift)   to create a new network namespace and launch applications that I want tunneled from a shell that is set to that network namespace. The challenge becomes the dns leaks when using `systemd-resolved`

**Comment by alextrekov3307** [comment]
There is: https://www.wireguard.com/netns/
The second use case where the physical interfaces get ejected from the default namespace is most suitable for those who don't practice more paranoid isolation or use multiple tunnels for multiple applications.

And for resolv: http://man7.org/linux/man-pages/man8/ip-netns.8.html

There is also firejail where you can specify both netns and dns.

**Comment by jonpolak** [comment]
@alextrekov3307  thanks for the `netns` link. It is indeed what I'm seeking to do. What modifications would you make to the `conf` files sent by vpn providers means to be used with `wg-quick`

**Comment by pirate** [comment]
Figured out how to do this with docker: https://github.com/pirate/wireguard-docs#containerization

If you can get your application running inside a docker container, then you can route all of its traffic through wireguard like this:

**`docker-compose.yml`:**
```yaml
version: '3'

services:
  wireguard:
    image: linuxserver/wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    volumes:
      - /lib/modules:/lib/modules
      - ./wg0.conf:/config/wg0.conf:ro

  vpn_test:
    image: curlimages/curl
    entrypoint: curl -s http://whatismyip.akamai.com/
    network_mode: 'service:wireguard'
```
**`wg0.conf`**:
```
[Interface]
# Name = client1.wg.example.com
Address = 10.17.17.2/32
PrivateKey = abc...

[Peer]
# Name = relay1.wg.example.com
Endpoint = relay1.wg.example.com:51820
PublicKey = abc...
AllowedIPs = 0.0.0.0/0
PersistentKeepalive = 21
```

```bash
docker-compose up
docker-compose run vpn_test
# should output public IP of VPN relay server (instead of container host)
```
